name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: install dependencies
        run: |
          sudo apt-get -y install \
            build-essential \
            autoconf \
            autoconf-archive \
            automake \
            libtool \
            gtk-doc-tools \
            libglib2.0-dev \
            libgtk-3-dev \
            libsoup-3.0-dev \
            libgirepository1.0-dev
      - uses: actions/checkout@v2
      - name: autogen
        run: ./autogen.sh
      - name: configure prefix
        run: ./configure --prefix /usr
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
      - name: make install
        run: sudo make install
      - name: install test dependencies
        run: |
          sudo apt-get -y install \
            python3-gi \
            python3-cairo \
            gir1.2-gtk-3.0 \
            gir1.2-gdkpixbuf-2.0 \
            xvfb
      - name: run python unittest
        run: xvfb-run --auto-servernum /usr/bin/python3 -m unittest discover -v tests/
